### ISSUE TITLE
Multiple tcpConnections don't work

### ISSUE THREAD

**Issue by maacarbo** [slem1/await-maven-plugin#1]
When testing two connections in the configuration only the first one is being taken into account.
```
<plugin>
    <groupId>com.github.slem1</groupId>
    <artifactId>await-maven-plugin</artifactId>
    <version>1.0</version>
    <executions>
        <execution>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>Await</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <poll>
            <attempts>5</attempts>
            <sleep>5000</sleep>
        </poll>
        <tcpConnections>
            <tcpConnection>
                <host>localhost</host>
                <port>9092</port>
            </tcpConnection>
            <tcpConnection>
                <host>localhost</host>
                <port>6379</port>
            </tcpConnection>
        </tcpConnections>
    </configuration>
</plugin>
```

**Comment by maacarbo** [comment]
Made it work by adding a different priority per tcpConnection tag.
Maybe the `new TreeSet<>(TASK_PRIORITY_COMPARATOR);` mechanism should be updated by not only considering a priority and also taking into account the index in the list?

**Comment by slem1** [comment]
Hi, i'm glad you managed to solve this.
I guess managing both priority and index order could made things a bit messy if some connections have priority and others not. But maybe it was overkill to handle priorities whereas the order of declaration should be okay in most of cases. for the time being, I'm going to update the documentation.

**Comment by slem1** [comment]
Actually I misread your first post. It's due to bad usage of Set here. I'm going to fix it

**Comment by maacarbo** [comment]
Idd.
Th priority might be interesting while mixing both TCP en HTTP conditions.

**Comment by slem1** [comment]
I just published a snapshot version which should fix the issue.

``` xml
   <dependency>
            <groupId>com.github.slem1</groupId>
            <artifactId>await-maven-plugin</artifactId>
            <version>1.1-SNAPSHOT</version>
        </dependency>
```

It replace the collection for PollingTasks with a List. The list is sorted by priority. If you don't specify the priority it should be 0 (the max). It should not swallow same priority connections like the former TreeSet implementation.

**Comment by slem1** [comment]
@maacarbo can you try getting the snapshot dependency ? please tell me if it's ok.

**Comment by slem1** [comment]
Pull request: #2

**Comment by maacarbo** [comment]
It is working now. Thanks!
But for me, it would sound more logic that if not specified, it would get lowest priority, no?

**Comment by slem1** [comment]
Yes you're right, I just build a new snapshot which changed this behavior. It should be available. If you try it please let me know. After that I'll release the version. Thank you !

**Comment by slem1** [comment]
Fixed version: 1.1

**Comment by maacarbo** [comment]
Sorry for the late response. Was on holiday until yesterday.
I tested version 1.2 and it works like expected! Thank you a lot!

**Comment by slem1** [comment]
^^ no pb
-- 
Sylvain Lemoine
